### ISSUE TITLE
RSS outside USA

### ISSUE THREAD

**Issue by yo2ldk** [RandomArray/wifiweather#1]
Hi, nice project !
It is possible to add (obtain) RSS data somehow, for a outside USA country?
 Thank you in advance !

**Comment by RandomArray** [comment]
Currently the php script (`getweather.php`) is parsing an XML feed and placing it into the `$data[]` array. First it converts the XML with `simplexml_load_string`. We then filp the data to JSON before decoding it and placing it in the `$data[]` array. 

I've included the relevant piece of code below. This would need to be changed to parse the RSS feed and place the bits of data into the `$data[]` array. 

The most important part is finding a data source. What country/city do you need data for? Have you found a data feed in XML, JSON, CSV, RSS, etc...?

```
$url = 'http://w1.weather.gov/xml/current_obs/KMYF.xml';
// Get XML Data, Convert to array
$xmldata = getUrlContent($url);
$xml = simplexml_load_string($xmldata);
$json = json_encode($xml);
$data = json_decode($json,TRUE);
```
